fix the call getCursor error
When call the getCursor function, it will throw the following exception, just need to use the com.mongodb.Cursor to solve this problem.
java.lang.ClassCastException: com.mongodb.MongoCursorAdapter cannot be cast to com.mongodb.DBCursor
	at org.mongodb.morphia.query.MorphiaIterator.getCursor(MorphiaIterator.java:76)